[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = {sepolia-eth ="https://eth-sepolia.g.alchemy.com/v2/Mfmh9MT9fLAxMiCtkYHgwLYDnqUMC-Ot", arb-sepolia="https://arb-sepolia.g.alchemy.com/v2/rQYeVIr2PgHfS9GA0RJNP"}

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/chainlink/",
    "@chainlink-local/=lib/chainlink-local/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
